
spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: gumiho-z-gateway


management:
  security:
    enabled: false
security:
  basic:
    enabled: false

info:
  z-gateway:
    version: "@project.version@"
    profile: "@spring.profiles.active@"
    date: 20180905


---
server:
  port: 80
  context-path: /

spring:
  profiles: local
  redis:
    database: 10
    host: 192.168.1.245
    port: 6379
    password:
zuul:
  #ignored-patterns: /**/userRegister/**,/**/login/**,/**/swagger-ui.html,/**/static/**
  routes:
    gumiho-a-personally:
      path: /personally/**
      stripPrefix: false
      sensitiveHeaders:
    gumiho-a-shop:
      path: /shop/**
      stripPrefix: false
      sensitiveHeaders:
    gumiho-a-etc:
      path: /etc/**
      stripPrefix: false
      sensitiveHeaders:
    gumiho-a-service:
      path: /service/**
      stripPrefix: false
      sensitiveHeaders:
    gumiho-a-helper:
      path: /helper/**
      stripPrefix: false
      sensitiveHeaders:
    gumiho-a-promotion:
      path: /promotion/**
      stripPrefix: false
      sensitiveHeaders:
  add-proxy-headers: true
  ignored-services: '*'
  force-original-query-string-encoding: false
  add-host-header: true
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

  SendErrorFilter:
    post:
      disable: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.242:8761/eureka/,http://192.168.1.243:8761/eureka/,http://192.168.1.244:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
logging:
  config: classpath:log4j2-local.yml
---

server:
  port: 80
  context-path: /

spring:
  profiles: dev
  redis:
    database: 10
    host: 192.168.1.245
    port: 6379
    password:
zuul:
  #ignored-patterns: /**/userRegister/**,/**/login/**,/**/swagger-ui.html,/**/static/**
  routes:
    gumiho-a-personally:
      path: /personally/**
      stripPrefix: false
      sensitiveHeaders:
    gumiho-a-shop:
      path: /shop/**
      stripPrefix: false
      sensitiveHeaders:
    gumiho-a-etc:
      path: /etc/**
      stripPrefix: false
      sensitiveHeaders:
    gumiho-a-service:
      path: /service/**
      stripPrefix: false
      sensitiveHeaders:
    gumiho-a-helper:
      path: /helper/**
      stripPrefix: false
      sensitiveHeaders:
    gumiho-a-promotion:
      path: /promotion/**
      stripPrefix: false
      sensitiveHeaders:
  add-proxy-headers: true
  ignored-services: '*'
  force-original-query-string-encoding: false
  add-host-header: true
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

  SendErrorFilter:
    post:
      disable: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.242:8761/eureka/,http://192.168.1.243:8761/eureka/,http://192.168.1.244:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
logging:
  config: classpath:log4j2-dev.yml

---
server:
  port: 80
  context-path: /

spring:
  profiles: test
  redis:
    database: 10
    host: 192.168.1.75
    port: 6379
    password:
zuul:
  #ignored-patterns: /**/userRegister/**,/**/login/**,/**/swagger-ui.html,/**/static/**
  routes:
    gumiho-a-personally:
      path: /personally/**
      stripPrefix: false
      sensitiveHeaders:
    gumiho-a-shop:
      path: /shop/**
      stripPrefix: false
      sensitiveHeaders:
    gumiho-a-etc:
      path: /etc/**
      stripPrefix: false
      sensitiveHeaders:
    gumiho-a-service:
      path: /service/**
      stripPrefix: false
      sensitiveHeaders:
    gumiho-a-helper:
      path: /helper/**
      stripPrefix: false
      sensitiveHeaders:
    gumiho-a-promotion:
      path: /promotion/**
      stripPrefix: false
      sensitiveHeaders:
  add-proxy-headers: true
  ignored-services: '*'
  force-original-query-string-encoding: false
  add-host-header: true
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

  SendErrorFilter:
    post:
      disable: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.77:8761/eureka/,http://192.168.1.78:8761/eureka/,http://192.168.1.79:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

logging:
  config: classpath:log4j2-test.yml

---
server:
  port: 8000
  context-path: /

spring:
  profiles: online
  redis:
    database: 10
    host: r-2zec535448999e24.redis.rds.aliyuncs.com
    port: 6379
    password: REDISdh2018
zuul:
  #ignored-patterns: /**/userRegister/**,/**/login/**,/**/swagger-ui.html,/**/static/**
  routes:
    gumiho-a-personally:
      path: /personally/**
      stripPrefix: false
      sensitiveHeaders:
    gumiho-a-shop:
      path: /shop/**
      stripPrefix: false
      sensitiveHeaders:
    gumiho-a-etc:
      path: /etc/**
      stripPrefix: false
      sensitiveHeaders:
    gumiho-a-service:
      path: /service/**
      stripPrefix: false
      sensitiveHeaders:
    gumiho-a-helper:
      path: /helper/**
      stripPrefix: false
      sensitiveHeaders:
    gumiho-a-promotion:
      path: /promotion/**
      stripPrefix: false
      sensitiveHeaders:
  add-proxy-headers: true
  ignored-services: '*'
  force-original-query-string-encoding: false
  add-host-header: true
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

  SendErrorFilter:
    post:
      disable: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

eureka:
  client:
    serviceUrl:
        defaultZone: http://172.17.248.165:8761/eureka/,http://172.17.248.166:8761/eureka/,http://172.17.248.167:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
logging:
  config: classpath:log4j2-online.yml