server:
  port: 9990
eureka:
    client:
      serviceUrl:
        defaultZone: http://192.168.1.242:8761/eureka/,http://192.168.1.243:8761/eureka/,http://192.168.1.244:8761/eureka/
spring:
  application:
    name: task-tfs
  rabbitmq: #mq信息
    host: 192.168.1.246 #rabbitmq.dh.com
    port: 5672
    username: admin
    password: admin
    virtual-host: test
    publisher-returns: true
    publisher-confirms: true
    cache:
      channel:
        size: 50

#DB Configuration:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.204:3306/test_tianfs
    username: live
    password: live
#JPA Configuration:
  #jpa:
    #database: mysql
    #show-sql: true
    #generate-ddl: true

#DB Configuration:
#spring.datasource.driverClassName=com.mysql.jdbc.Driver
#spring.datasource.url = jdbc:mysql://192.168.1.204:3306/test_tianfs
#spring.datasource.username = live
#spring.datasource.password = live

#JPA Configuration:
#spring.jpa.database=MySQL
#spring.jpa.show-sql=true
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
#spring.jpa.hibernate.naming_strategy=org.hibernate.cfg.ImprovedNamingStrategy
#spring.jpa.database=org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MYSQL5Dialect