
---

server:
  port: 8844
  context-path: /


spring:
  profiles: online
  redis:
    database: 11
    host: r-2zec535448999e24.redis.rds.aliyuncs.com
    port: 6379
    password: REDISdh2018
  rabbitmq:
    host: 172.17.248.176
    port: 5670
    username: hystrix
    password: hystrix
    virtual-host: hystrix

logging:
  config: classpath:log4j2-online.yml

zuul:
  routes:
    gumiho-w-admin-user:
      path: /oxr/**
      stripPrefix: true
      sensitive-headers: xsrf-token,Authorization
    gumiho-w-background:
      path: /nice/**
      stripPrefix: true
      sensitive-headers: xsrf-token,Authorization
    gumiho-w-b2b:
      path: /oxbl/**
      stripPrefix: true
      sensitive-headers: xsrf-token,Authorization
    gumiho-w-b2bnational:
      path: /oxbc/**
      stripPrefix: true
      sensitive-headers: xsrf-token,Authorization
    gumiho-w-b2c:
      path: /oxc/**
      stripPrefix: true
      sensitive-headers: xsrf-token,Authorization
    gumiho-w-service:
      path: /oxf/**
      stripPrefix: true
      sensitive-headers: xsrf-token,Authorization
    gumiho-w-operating:
      path: /oxy/**
      stripPrefix: true
      sensitive-headers: xsrf-token,Authorization
    gumiho-w-teminal:
      path: /oxm/**
      stripPrefix: true
      sensitive-headers: xsrf-token,Authorization

 # add-proxy-headers: true
  ignored-services: '*'
  force-original-query-string-encoding: false
  add-host-header: true
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 6000


eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.248.165:8761/eureka/,http://172.17.248.166:8761/eureka/,http://172.17.248.167:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}



security:
  oauth2:
    client:
      accessTokenUri: https://oauth.oxnice.com/uaa/oauth/token
      userAuthorizationUri: https://oauth.oxnice.com/uaa/oauth/authorize
      clientId: zuul
      clientSecret: zuul
      scope: all
      id: zull
      registered-redirect-uri:
    resource:
      id: zuul
      token-info-uri: https://oauth.oxnice.com/uaa/oauth/check_token
      user-info-uri: https://oauth.oxnice.com/uaa/oauth/user
    sso:
      login-path: /login
      logout: https://oauth.oxnice.com/uaa/logout?token=
  basic:
    enabled: true
  user:
    password: ly
    name: ly
gumiho-s-merchant:
  url: