
---
server:
  port: 8888
  context-path: /

spring:
  profiles: online
  rabbitmq:
    host: 172.17.248.176
    port: 5670
    username: hystrix
    password: hystrix
    virtual-host: hystrix
  redis:
    database: 11
    host: r-2zec535448999e24.redis.rds.aliyuncs.com
    port: 6379
    password: REDISdh2018
logging:
  config: classpath:log4j2-online.yml
feignclient:
  url:

eureka:
  client:
    serviceUrl:
        defaultZone: http://172.17.248.165:8761/eureka/,http://172.17.248.166:8761/eureka/,http://172.17.248.167:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

ctx:
  value: /oxr
