---
server:
  port: 8888
  context-path: /
#  session:
#    cookie:
#      name: zuuloauth


spring:
  profiles: test

  redis:
    database: 11
    host: 192.168.1.75
    port: 6379
    password:

  rabbitmq:
    host: 192.168.1.210
    port: 5670
    username: hystrix
    password: hystrix
    virtual-host: hystrix

logging:
  config: classpath:log4j2-test.yml

feignclient:
  url:

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.77:8761/eureka/,http://192.168.1.78:8761/eureka/,http://192.168.1.79:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
ctx:
  value: /oxr

