
---
server:
  port: 3334
  context-path: /

spring:
  profiles: online
  datasource:
    name: admin
    url: jdbc:mysql://rm-2zeyaj6809tr8o013.mysql.rds.aliyuncs.com/gumiho_admin_user?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=true&allowMultiQueries=true
    username: admin_user
    password: admin_user123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 172.17.248.176
    port: 5670
    username: hystrix
    password: hystrix
    virtual-host: hystrix
  redis:
    database: 11
    host: r-2zec535448999e24.redis.rds.aliyuncs.com
    port: 6379
    password: REDISdh2018

gumiho-s-merchant:
  url:
gumiho-s-allinpay:
  url: #127.0.0.1:9876

logging:
  config: classpath:log4j2-online.yml

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  #type-aliases-package: classpath:cn.com.myproject.user.entity
  config-location: classpath:mybatis-config.xml
eureka:
  client:
    serviceUrl:
        defaultZone: http://172.17.248.165:8761/eureka/,http://172.17.248.166:8761/eureka/,http://172.17.248.167:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
