
server:
  port: 3334
  context-path: /


mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  #type-aliases-package: classpath:cn.com.myproject.user.entity
  config-location: classpath:mybatis-config.xml

logging:
  config: classpath:log4j2.yml


pagehelper:
  params: pageNum=pageNumKey;pageSize=pageSizeKey;

aliyun:
  oss:
    endpoint: oss-cn-hongkong.aliyuncs.com
    access-key-secret: XWwSMQFfcFEisPBJXoYOoGuDHwL66N
    access-key-id: LTAIPOcxLTWiB6yH
    bucket-name: sjjimg
    return-url-prefix: http://a.myproject.com.cn/
  push:
    app-key: 24613456
    app-secret: uAyhEQoaypoEPy9zFU4fAY7aj9TmrH
    app-key-id: LTAIWPmZiJa5FSdO
    region-id: cn-hangzhou
    i-o-s-apns-env: PRODUCT

spring:
  application:
    name: gumiho-admin-user
  datasource:
    name: admin
    url: jdbc:mysql://mysql01.dh.com:3306/cloud_auth?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=true&allowMultiQueries=true
    username: cloud
    password: cloud
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      max-active: 20
      initial-size: 3
      min-idle: 1
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      use-global-data-source-stat: true
  redis:
    database: 11
    host: redis01.dh.com
    port: 6379
    password:
  rabbitmq:
    host: rabbitmq.dh.com
    port: 5672
    username: hystrix
    password: hystrix
    virtual-host: hystrix

eureka:
  client:
    service-url:
      defaultZone: http://eureka242.dh.com:8761/eureka/,http://eureka243.dh.com:8761/eureka/,http://eureka244.dh.com:8761/eureka/
    register-with-eureka: true
  instance:
    prefer-ip-address: true

    #instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}


